#define PJ_CONFIG_MINIMAL_SIZE
#define PJMEDIA_HAS_VIDEO 1
#define PJMEDIA_HAS_LIBYUV 1
#define PJMEDIA_HAS_OPENH264_CODEC 1
#define PJMEDIA_HAS_VPX_CODEC 1
#define PJMEDIA_VIDEO_DEV_HAS_SDL 1
#define PJMEDIA_VIDEO_DEV_HAS_DSHOW 1
#define PJMEDIA_VIDEO_DEV_SDL_HAS_OPENGL 1
#define PJMEDIA_HAS_OPUS_CODEC 1
#define PJMEDIA_HAS_BCG729 1
#define BCG729_STATIC
#define PJ_HAS_SSL_SOCK 1

#include "config_site_sample.h"