#define PJ_CONFIG_MINIMAL_SIZE
#define PJMEDIA_HAS_VIDEO 1
#define PJMEDIA_HAS_FFMPEG 0
#define PJMEDIA_HAS_OPENH264_CODEC 1
#define PJMEDIA_HAS_VPX_CODEC 1
#define PJMEDIA_HAS_OPUS_CODEC  1
#define PJMEDIA_HAS_BCG729 1
#define PJ_HAS_SSL_SOCK 1
#define PJ_HAS_LIMITS_H 1

#include "config_site_sample.h"
